// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"MutationObser","status":false,"description":"h5桥接PIXI的文本驱动UI框架","parameters":{"DKTools.Localization:{}":"false","SimpleWorkEditor":"false"}},
{"name":"vue","status":false,"description":"","parameters":{}},
{"name":"vue2pixi","status":false,"description":"","parameters":{}},
{"name":"MutationObser copy","status":false,"description":"","parameters":{}}
];
